name: Release

on:
  workflow_dispatch:

env:
  BINARY_NAME: cyberlite
  CARGO_TERM_COLOR: always

jobs:
  generate-version:
    name: Generate version
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.next.outputs.minor }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get previous tag
        id: previous
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: v0.0.0

      - name: Get next minor version
        id: next
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.previous.outputs.tag }}

  build-and-upload:
    name: Build and upload
    runs-on: windows-latest
    needs: generate-version
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: Swatinem/rust-cache@v2

      # TODO: make binary as fast/small as possible, e.g. with strip
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Compress
        shell: pwsh
        run: |
          Move-Item -Path target/release/${{ env.BINARY_NAME }}.exe -Destination ${{ env.BINARY_NAME }}.exe
          7z a -tzip ${{ env.BINARY_NAME }}.zip assets ${{ env.BINARY_NAME }}.exe

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ needs.generate-version.outputs.version }}
          generateReleaseNotes: true
          artifacts: ${{ env.BINARY_NAME }}.zip
